version: "3.3"
services:
  angularjs_app:
    build:
      context: ./angularjs-demo
      dockerfile: Dockerfile.prod
    ports:
      - 81:80

  angular8_app:
    build:
      context: angular8-demo
      dockerfile: Dockerfile.prod
    ports:
      - 82:80

  nginx_proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - angular8_app
      - angularjs_app
